### ISSUE TITLE
error while building message: Payload is too big.

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [vti/protocol-websocket#24]
i'm getting the following error after the module got updated to 0.002001

```
error while building message: Payload is too big. Send shorter messages or increase max_payload_size at /usr/local/share/perl/5.14.2/Protocol/WebSocket/Frame.pm line 232.
```

this didn't happen before. extra info:

```
$ perl -MNet::WebSocket::Server -e 'print "$Net::WebSocket::Server::VERSION\n"'
0.002001
```

can you make the max_payload_size configurable?

**Comment by randomandy** [comment]
Sorry for commenting on a closed issue.
How do you set the payload size in the Frame constructor?

There's nothing on that in the docs:
http://search.cpan.org/~vti/Protocol-WebSocket-0.18/lib/Protocol/WebSocket/Frame.pm

**Comment by vti** [comment]
`new(max_payload_size => NUMBER)` should work. Yeah, docs could be better.
